name: ci
on:
  release:
    types: [published]
    tag:
    - v1.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: aungkokokhant/randnumimg:v1.0
      -
        name: Post message on slack
        uses: bluenovaio/action-slack@main
        with:
          username: "Aung Ko Ko Khant"
          icon_emoji: ":robot_face:"
          text:  "Name: Aung Ko Ko Khant \nMatriculation: A0249480X \nEmail: <outlook.com| e0941673@u.nus.edu > \nRepo: <https://github.com/Crystallozti/randomnum.git|git@github.com:Crystallozti/randomnum.git>\nImage name: nyan345/randnumimg:${{github.ref_name}}\nImage url: <https://hub.docker.com/repository/docker/aungkokokhant/randnumimg|https://hub.docker.com/repository/docker/aungkokokhant/randnumimg>"
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}